version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.11.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  cassandra:
    image: cassandra
    ports:
      - 7000:7000
      - 9042:9042
  setup:
    image: cassandra
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 20 && cqlsh cassandra < /models/schema.cql" ]
    volumes:
      - ./cassandra:/models
