version: "3.4"
services:
  elasticsearch:
    image: elasticsearch:7.11.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
  setup_es:
    image: micarlise/container-tools:base
    depends_on:
      - elasticsearch
    restart: "no"
    command: [ "wait-for-it.sh", "elasticsearch:9200", "--", "curl", "-X", "PUT", "elasticsearch:9200/photos" ]
  setup_cassy:
    image: cassandra
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "bash", "-c", "sleep 20 && cqlsh cassandra < /models/schema.cql" ]
    volumes:
      - ./cassandra:/models
